export const fundingInstructionsPageTemplate = () => {
  return `FUNDING INSTRUCTIONS
_______________________________________________________________________

The instructions in this section tell you how to transfer various types of assets. You must transfer the assets that you currently own and that you acquire in the future to your Revocable Living Trust. This transfer is vitally important.

If you ever need any assistance in transferring assets to your Revocable Living Trust, do not hesitate to make an appointment with our office. It is your responsibility to ensure that all of your property is transferred to your Revocable Living Trust.

[PAGE_BREAK]

Revocable Living Trust Funding Instructions for {{TRUST_NAME}}

We cannot overemphasize the importance of having a fully funded Revocable Living Trust. An unfunded or partially funded Revocable Living Trust does not avoid probate. These instructions will help you fund your Revocable Living Trust.

    • You will make ownership changes to change the title of most of your assets from your name as an individual to your name as Trustee of your Revocable Living Trust.

    • For other assets, such as life insurance and retirement accounts, you will make beneficiary changes to properly distribute those assets upon your death. The beneficiary will not necessarily be your Revocable Living Trust –please see the Retirement Plans and Life Insurance Policies and Annuities sections of this document.

Generally, to transfer assets to your trust, you must execute new documents of title, deeds to real property, and signature cards for your bank accounts, as well as change of beneficiary forms for pension plans, individual retirement plans and life insurance.

Your financial advisor, accountant, broker, or life insurance agent may need to help you make ownership or beneficiary changes. These instructions will give you general knowledge of how to fund your trust, but they cannot comprehensively address every type of transfer. Please call us if you must make transfers that are not addressed in these instructions.

We recommend you place copies of all written documents which evidence the interest of your Revocable Living Trust into your Revocable Living Trust Portfolio. These assets may include your accounts, real property, business interests, insurance policy proceeds, or any other property. Your final step in the transfer process should always be to place a document in the TRUST ASSETS section of your Revocable Living Trust Portfolio that proves your trust is the owner or beneficiary of each asset. The bolded, italicized sentence ending the transfer instructions for each type of asset tells you what documents to put into your Revocable Living Trust Portfolio.

Using Your Certification of Trust

Your Revocable Living Trust Portfolio contains a Certification of Trust. In your certification, you state in writing that:

    your trust exists;
    you are one of the Trustees; and
    you have the authority and power to transact business as a Trustee.

Most institutions have their own certification forms for you to fill out. If the institution you are dealing with does not have a form, you should provide them with a copy of your Certification of Trust form. Your Certification of Trust provides only the information that the persons you deal with need to see without disclosing confidential details.

Your Tax Identification Number

As long as you are acting as Trustee of your Revocable Living Trust, you do not need to obtain a separate tax identification number for your trust or to file a separate trust tax return. The Internal Revenue Service (IRS) prefers that you use your own Social Security number. You should report all of the income generated by trust assets on your personal IRS Form 1040 and California Form 540.

When you die, your trust becomes irrevocable for tax purposes. It may split into multiple trusts, each of which may be treated as a separate taxable entity for income tax purposes. We will work with your successor Trustee and your accountant to see that your heirs get the full benefit of your estate planning upon your death.

Titling Assets in Your Name as Trustee

Generally, you should title all of your currently owned and newly acquired assets in the name of your trust. We prefer the following format for titling assets in the name of your trust:

{{CLIENT_FULL_NAME}}{{#IF_JOINT}} and {{SPOUSE_FULL_NAME}}{{/IF_JOINT}}, Trustees, or their successors in interest, of {{TRUST_NAME}} dated {{TRUST_DATE_FORMATTED}}, and any amendments thereto.

Instructions for Transferring Specific Assets

Cash Accounts

You should sign new signature and ownership cards to retitle any sizeable bank accounts or cash equivalents, including treasury bills, money market accounts, and certificates of deposit, to name yourself as Trustee of those accounts. You need not change any small joint or other checking accounts used primarily for household expenses.

Before you retitle your certificates of deposit, consult with a bank officer to make sure that the institution does not consider the change in account name to be an early withdrawal that incurs a penalty. Generally, this should not be a problem because your tax identification number for the account will remain the same.

Instruct your financial institution by letter or in person to change the title to your trust. The tax identification number (your Social Security number) on the account for withholding and reporting purposes will remain the same. For joint trustee trusts, be sure to give each trustee signature power with respect to the account. Sign the new signature cards as Trustees.

Retitling the account records should have no effect on the name you wish to have printed on your checks. There is no reason to have the name of your trust on your printed checks. Ask your bank to continue to print your individual name on the checks.

After changing title, your next account statement will confirm the retitling by listing you as Trustee of your trust. Please put a copy of this account statement in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Investment Accounts

If you hold publicly traded stocks and bonds that are already in brokerage or investment accounts, contact your brokers or custodians and direct them to change the title of the accounts to the name of your trust. The procedure for doing so is the same as the procedure for retitling cash accounts explained above. You may have to complete new account applications and present a copy of your Affidavit or Certification of Trust in order to change the title. Title to the accounts should be in the trust name.

After changing title, your next account statement will confirm the retitling by listing you as Trustee of your trust. Please put a copy of this account statement in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Stocks and Bonds Not Held in Investment Accounts

If you possess original stock or bond certificates, there are two ways to transfer the certificates to your trust.

    • Open a brokerage or investment account in the name of your Revocable Living Trust and deposit your original certificates in the account. (You may later have your broker deliver the certificates to you made out in the name of the trust if you wish.) Your future account statements that will be titled in the name of your Revocable Living Trust will prove your ownership of the transferred stock or bonds. Please be sure to put a copy of an account statement proving ownership by the trust into the TRUST ASSETS section of your Revocable Living Trust Portfolio.

    • Work directly with the transfer agent for the stock or bond and direct the agent to reissue your stock with your Revocable Living Trust named as the new owner. Please put a copy of both the front and back of the new bond or stock certificate in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Stock Options

Transferring or assigning stock options requires a careful analysis of the tax and legal issues. We recommend you ask your Certified Public Accountant (CPA) and your stock plan administrator about your choices in assigning your interests to your Revocable Living Trust. If you would like us to assist you, we would be willing to do so under a separate representation agreement.

Personal Effects

Tangible personal property refers to such items as household furnishings, appliances and fixtures, works of art, motor vehicles, pictures, collectibles, personal wearing apparel and jewelry, books, sporting goods, and hobby paraphernalia. Your tangible personal property has been transferred to your Revocable Living Trust by declaration in Article One of the Trust.

Your personal vehicles can be titled in the name of your Revocable Living Trust, but we find that most of our clients prefer to leave their vehicles outside their trust for several reasons. One, if they have a vehicle accident, the fact they have a Revocable Living Trust could cause the other parties to the accident to assume they have deep pockets and encourage a lawsuit. Second, heirs can usually transfer vehicles without formal probate proceedings. If you decide to title your vehicle in the name of your trust, consult your casualty insurance agent to make certain the transfer will not result in a business rating on your insurance policy that would increase your premiums.

Retirement Plans

You should never transfer the ownership of a qualified retirement or pension plan or individual retirement account to your Revocable Living Trust. Instead, if you have pre-retirement death benefits under such a plan, our general recommendation is that you choose from among your spouse, children, or partner as primary and contingent beneficiaries.

Making the proper beneficiary designations for retirement plans involves many complex tax and individual family issues. Therefore, making a recommendation without further consultation is difficult. You have many tradeoffs to consider in naming your beneficiaries–tradeoffs that affect your required minimum distributions and the taxation of your benefits after your death.

If you would like to discuss the issues and solutions for designating your retirement plan beneficiaries to best match your unique goals, we would be pleased to do so. But this additional planning must be done under a subsequent written representation agreement.

Your retirement plan administrator should send you a letter confirming the change of beneficiaries in your retirement plan records. Please put a copy of this confirmation letter in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Qualified Tuition Plans (529 Plans)

Transferring a 529 plan to your Revocable Living Trust often makes sense, but your trust must contain specific language enabling the Trustee to manage the account. We recommend that you contact us before naming your trust as an owner of a 529 plan.

Life Insurance Policies and Annuities

You may want to tax-proof your major life insurance policies by creating one or more irrevocable life insurance trusts. In any event, you will probably want some policy proceeds paid directly to your Revocable Living Trust. Please consult with us so we can help you determine the proper ownership and beneficiary designation for each.

If you decide to name your Revocable Living Trust as the beneficiary of a policy, here are several points you should consider.

Your policy beneficiary designation, not your Will and Revocable Living Trust, controls the disposition of the policy benefits.

Generally, you should designate your Revocable Living Trust as the beneficiary of your life insurance policies so the policy proceeds will be governed by the terms of the Revocable Living Trust. To do so, we recommend you advise your insurance agent that you want your Revocable Living Trust as the beneficiary. Your agent will make the change for you or provide you the beneficiary designation form for you to complete.

If you name your Revocable Living Trust as the primary beneficiary, you should name your spouse, partner, or children as the secondary beneficiary.

Each insurance company will have its own preferred format for designating your Revocable Living Trust as the beneficiary. Here is a typical format:

    Primary Beneficiary: The {{TRUST_NAME}} dated {{TRUST_DATE_FORMATTED}}
    Secondary Beneficiary: Spouse, partner, children, or other heirs.

Your insurance company should send you a letter confirming the change of beneficiaries in your insurance policy or annuity records. Please put a copy of this confirmation letter in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Mortgage, Notes, and Other Receivables

If you have loaned money to anyone, you should assign your interest as lender to your Revocable Living Trust by a written document and notify your debtor of the assignment. We can prepare assignment documents for each interest for your signature. Please put a copy of each assignment in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Partnership Interest

If there are no restrictions in your general partnership agreement, your interest in the general partnership should be transferred through a written assignment of interest signed by you and acknowledged by your partners. Transfer of an interest in a limited partnership is accomplished in the same way as the transfer of a general partnership interest.

We can prepare assignment documents for each interest for your signature. Please put a copy of each assignment in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Corporate Business or Professional Interests

You should contact your corporate counsel or ask us to assist you in transferring your professional business interests to the Revocable Living Trust.

    • If your business is a corporation, you will have to cancel shares held in your name and reissue them in your name as Trustee of your Revocable Living Trust. Please put a copy of both the front and back of the new stock certificate in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

    • If your business is a limited liability company, we will draft assignment documents to assign your interest to your Revocable Living Trust. Please put a copy of the assignment in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Sole Proprietorship Business Interests

A sole proprietorship is a business entity owned by one person. Ownership of a sole proprietorship can be transferred to a Revocable Living Trust with a written assignment of interest. All items of tangible personal property should be listed individually or by category in the assignment. Please put a copy of the assignment in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Oil, Gas, and Mineral Interests

The method of transferring interests in oil, minerals, and gas depends on whether you own or lease the interests. Generally, if you own the interests, you should record a deed that titles your interests to your Revocable Living Trust. If your interest is a lease, you should assign your rights as a lessee to your Revocable Living Trust by a written assignment. Please put a copy of the deed or assignment in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Real Property

Transferring your real property to your trust will require attention to ownership and tax issues based on the nature of the current title to the property. Ultimately, the transfer will require preparing, executing, and recording new deeds for each property. This should be done through an attorney. At your request, we will assist you with this. Please put a copy of each deed in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Regarding your homeowner's policy, contact your insurance provider to discuss adding your trust as an additional endorsee on your policy.

Anticipated Inheritance, Gift, or Lawsuit Judgment

If you are the beneficiary of an estate of someone who has already died, or if you are a plaintiff in a lawsuit, you can assign your interest in the estate or lawsuit to your Revocable Living Trust in case you are disabled or deceased before receiving distributions or payments. Please put a copy of the assignment in the TRUST ASSETS section of your Revocable Living Trust Portfolio.

Reviewing Your Estate Plan

You should review your estate plan with an attorney every two to three years because all estate plans require on-going maintenance. In particular, a change in your family, an increase in your net worth, or a change in the tax law could significantly affect the effectiveness of your plan.`;
};
